using HealthPadiWebApi.DTOs;
using HealthPadiWebApi.Models;
using HealthPadiWebApi.Services.Interfaces;

namespace HealthPadiWebApi.Services.Implementations
{
    public class WeeklyTaskService : BackgroundService
    {
        private readonly ILogger<WeeklyTaskService> _logger;
        private readonly IServiceScopeFactory _serviceScopeFactory;


        public WeeklyTaskService(ILogger<WeeklyTaskService> logger, IServiceScopeFactory serviceScopeFactory)
        {

            _logger = logger;
            _serviceScopeFactory = serviceScopeFactory;

        }
        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            await CheckAndRunMissedTask(stoppingToken);

            while (!stoppingToken.IsCancellationRequested)
            {
                try
                {
                    using (var scope = _serviceScopeFactory.CreateScope())
                    {
                        var taskExecutionLoggerService = scope.ServiceProvider.GetRequiredService<ITaskExecutionLoggerService>();

                        var currentDay = DateTime.Now.DayOfWeek;
                        var currentTime = DateTime.Now.TimeOfDay;

                        if (currentDay == DayOfWeek.Sunday && currentTime >= new TimeSpan(00, 00, 00) && currentTime < new TimeSpan(01, 00, 00))
                        {
                            await RunWeeklyTask(stoppingToken);
                            await taskExecutionLoggerService.AddTaskExecutionLog(new TaskExecutionLog { TaskExecutionLogId = Guid.NewGuid(), LastExecutionTime = DateTime.Now });
                        }
                    }

                    await Task.Delay(TimeSpan.FromHours(1), stoppingToken);

                }
                catch (Exception e)
                {
                    _logger.LogError(e, "Error occurred while Executing weekly task");
                }
            }
        }

        private async Task RunWeeklyTask(CancellationToken stoppingToken)
        {
            try
            {
                using (var scope = _serviceScopeFactory.CreateScope())
                {
                    var aiService = scope.ServiceProvider.GetRequiredService<IAIService>();
                    var feedService = scope.ServiceProvider.GetRequiredService<IFeedService>();
                    //call the AI service to generate health feeds
                    var healthFeed = await aiService.GenerateHealthFeeds();
                    if (string.IsNullOrEmpty(healthFeed))
                    {
                        _logger.LogWarning("No healthfeed generated by AI service");
                        return;
                    }

                    var healthFeedDto = new AddFeedDto
                    {
                        FeedContent = healthFeed
                    };
                    await feedService.AddFeedAsync(healthFeedDto);
                    _logger.LogInformation("Weekly task executed and Healthfeed saved to DB");
                }

            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error occurred while running weekly task");
            }
        }

        private async Task CheckAndRunMissedTask(CancellationToken stoppingToken)
        {
            try
            {
                using (var scope = _serviceScopeFactory.CreateScope())
                {
                    var taskExecutionLoggerService = scope.ServiceProvider.GetRequiredService<ITaskExecutionLoggerService>();

                    var currentDay = DateTime.Now.DayOfWeek;
                    var currentTime = DateTime.Now.TimeOfDay;

                    if (currentDay == DayOfWeek.Sunday && currentTime >= new TimeSpan(00, 00, 00) && currentTime < new TimeSpan(01, 00, 00))
                    {
                        return;
                    }


                    var logs = await taskExecutionLoggerService.GetAllTaskExecutionLogs();

                    var latestLog = logs.OrderByDescending(log => log.LastExecutionTime).FirstOrDefault();

                    if (latestLog != null)
                    {
                        var timeSinceLastExecution = DateTime.Now - latestLog.LastExecutionTime;
                        if (timeSinceLastExecution.TotalDays > 7)
                        {
                            await RunWeeklyTask(stoppingToken);
                        }
                    }
                }

            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error getting logged date for healthfeed");
            }
        }
    }
}